Small change to the window saga and reducer
avcopan/painless-panes pull request #40
Opened 2023-09-08 14:40 UTC by steveshumaker

Slight change to the add window saga. It now updates the store with just the ID of the current window rather than an array of objects containing window and project IDs - we can handle that with a separate query/route. I think ultimately this makes more sense for our purposes, at least currently.

2023-09-08 15:18 UTC, avcopan requested changes
Hey @steveshumaker, I see what you're doing and I agree that we need to track the current window in store, but this won't work as part of the `windows` store. That's because `windows` is storing info for all windows, whereas the current window is just a single ID, so calling `dispatch(actions.setCurrentWindow(5))` would wipe out the windows store.

Off the top of my head, I see two options:
1. Put the the "currentWindow" as part of the `user` store. So the `user` object in store could contain the `currentWindowId` in addition to the user's ID and email.
2. Have a separate `currentWindow` store with its own reducer.

I think I favor option 1. In that case, we could also store the `currentProjectId` as part of the user store, so that we know which project we are modifying.

2023-09-09 00:11 UTC, avcopan commented
> Hey @steveshumaker, I see what you're doing and I agree that we need to track the current window in store, but this won't work as part of the `windows` store. That's because `windows` is storing info for all windows, whereas the current window is just a single ID, so calling `dispatch(actions.setCurrentWindow(5))` would wipe out the windows store.
> 
> Off the top of my head, I see two options:
> 1. Put the the "currentWindow" as part of the `user` store. So the `user` object in store could contain the `currentWindowId` in addition to the user's ID and email.
> 2. Have a separate `currentWindow` store with its own reducer.
> 
> I think I favor option 1. In that case, we could also store the `currentProjectId` as part of the user store, so that we know which project we are modifying.

I ended up going with option 2, for the project/projects reducer because I realized that it might be confusing to try to keep extra things in the user store. Also, it gets overwritten on a reload.

2023-09-09 15:03 UTC, avcopan requested changes
Hey @steveshumaker I think this is almost ready. Sorry to be nitpicky and request changes again, but I think getting the redux store right will be important moving forward.

2023-09-09 15:03 UTC, avcopan commented on src/store/reducers/window.reducer.js
> +export function currentWindowReducer(state = [], action) {
The initial state for the current window should be an object `{}` rather than an array `[]`

2023-09-09 15:03 UTC, avcopan commented on src/store/sagas/window.saga.js
> +    yield put(updateWindows({ proj_id: project_id, window_id: windowId }));
Let's delete this `put(updateWindows())` call for now. I think it would be better to update the list of all windows using a GET request, to get all windows associated with the project. That way, we know we are fully synced up. Otherwise, if the user refreshes, the app will be missing windows from before the refresh.

2023-09-09 15:03 UTC, avcopan commented on src/store/sagas/window.saga.js
>      yield put(setCurrentWindow({ window_id: windowId }));
I think we should be storing the whole object (the whole database row) for the current window, rather than just the ID. Otherwise, we would need to store the other window information in a whole other store, which seems redundant.

2023-09-09 15:03 UTC, avcopan commented on src/store/sagas/window.saga.js
>      yield put(setCurrentWindow({ window_id: windowId }));
Also, since it's a "windows" object, let's just let `id` be the window ID (instead of `window_id`). This seems to be standard practice from what I've seen, and to me doing
```
const windowId = currentWindow.id;
```
makes more sense than having to do
```
const windowId = currentWindow.window_id;
```

2023-09-11 15:29 UTC, steveshumaker reviewed
Had a minute so reviewed and looks good to me. I think in the future we should try to ensure the larger PRs are closed so they don't blow up to 30+ files (inclusive of changes made on top of the PR)

2023-09-11 15:29 UTC, merged

2023-09-11 15:30 UTC, avcopan commented
> I think in the future we should try to ensure the larger PRs are closed so they don't blow up to 30+ files (inclusive of changes made on top of the PR)

Agreed! Sorry about that. I think folks missed my message requesting a review and merge before further PRs.